[build]
  publish = "public"
  command = "npm install && hugo --minify"

[build.environment]
  HUGO_VERSION = "0.111.0"
  NODE_VERSION = "18.19.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {ClientSideRendered = true}

[context.production.environment]
  HUGO_ENV = "production"
