[build]
  publish = "public"
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"

[build.environment]
  HUGO_VERSION = "0.111.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {ClientSideRendered = true}

[context.production.environment]
  HUGO_ENV = "production"
